### ISSUE TITLE
Resume test has a data race

### ISSUE THREAD

**Issue by cespare** [c4milo/gofetch#5]
FYI

```
$ go test -race -run Resume
==================
WARNING: DATA RACE
Read by goroutine 6:
  github.com/c4milo/gofetch.TestResume()
      /home/caleb/p/go/src/github.com/c4milo/gofetch/gofetch_test.go:129 +0x8db
  testing.tRunner()
      /home/caleb/apps/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 8:
  github.com/c4milo/gofetch.TestResume.func2()
      /home/caleb/p/go/src/github.com/c4milo/gofetch/gofetch_test.go:116 +0x15d

Goroutine 6 (running) created at:
  testing.RunTests()
      /home/caleb/apps/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /home/caleb/apps/go/src/testing/testing.go:494 +0xe4
  main.main()
      github.com/c4milo/gofetch/_test/_testmain.go:58 +0x20f

Goroutine 8 (finished) created at:
  github.com/c4milo/gofetch.TestResume()
      /home/caleb/p/go/src/github.com/c4milo/gofetch/gofetch_test.go:118 +0x70f
  testing.tRunner()
      /home/caleb/apps/go/src/testing/testing.go:456 +0xdc
==================
PASS
Found 1 data race(s)
exit status 66
FAIL    github.com/c4milo/gofetch       1.126s
```

**Comment by c4milo** [comment]
Hmm, I think that may be false positive. If you see here: https://github.com/c4milo/gofetch/blob/master/gofetch.go#L80 I'm closing the channel once there is no more data to write to the file and chunks were fully merged. So, my assumption is that https://github.com/c4milo/gofetch/blob/master/gofetch_test.go#L121-L124 is going to block until the channel is close and https://github.com/c4milo/gofetch/blob/master/gofetch_test.go#L129 shouldn't represent a race condition given that at that point there is no more writing happening on that file descriptor. 

What do you think?

**Comment by cespare** [comment]
The race detector has no false positives. It only reports races that actually occur.

**Comment by cespare** [comment]
In this case, the race is that you're calling `file.Stat()` concurrently with assigning `file` (`file, err = Fetch(...)`) without synchronization.

**Comment by c4milo** [comment]
That's my point, I don't see how in the code that would happen concurrently. Unless I'm misunderstanding Go's internals, the `select` statement should block reading from the `progress` channel until all writing is done to the file. `file.Stat()` happens just after the channel is closed which in turn only happens when all writing to the file is done.

**Comment by cespare** [comment]
It's not the writing to the file that's the race, it's assigning the result of `Fetch()` to `file, err`.

After the loop on lines 121-124 is done, you know that `Fetch()` has finished its work, but you don't know that it has actually returned or that `file, err` has been assigned. That's the race.

**Comment by c4milo** [comment]
I see it now! you are right. The chance of race condition lives between the invocation of the deferred function closing the channel and the return statement. Thanks god we have a race detector.

**Comment by c4milo** [comment]
@cespare thanks for walking through it with me. :+1:

**Comment by cespare** [comment]
You're welcome!
